FROM node:18-alpine AS frontend-builder

WORKDIR /app/frontend
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci --omit=dev
COPY frontend .
RUN npm run build

# Stage 2: Build FastAPI backend
FROM python:3.11-slim AS backend-builder

WORKDIR /app/backend
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend .

# Stage 3: Production image
FROM python:3.11-slim
WORKDIR /app

# Copy frontend (static files)
COPY --from=frontend-builder /app/frontend/.next /app/frontend/.next
COPY --from=frontend-builder /app/frontend/public /app/frontend/public
COPY --from=frontend-builder /app/frontend/package.json /app/frontend/

# Copy backend
COPY --from=backend-builder /app/backend /app/backend
COPY --from=backend-builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages

# Install frontend dependencies (for `next start`)
RUN apt-get update && apt-get install -y --no-install-recommends \
    nodejs \
    npm \
    && npm install -g serve \
    && rm -rf /var/lib/apt/lists/*

# Environment variables
ENV NEXT_TELEMETRY_DISABLED=1 \
    PYTHONUNBUFFERED=1 \
    MONGO_URI=mongodb://mongo:27017  # ← Replace with AWS DocumentDB URI

# Expose ports (Next.js: 3000, FastAPI: 8000)
EXPOSE 3000 8000

# Start both services (adjust for your process manager)
CMD sh -c "cd /app/frontend && npm run start & cd /app/backend && uvicorn main:app --host 0.0.0.0 --port 8000"