services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-2
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-2
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - app_network


  backend:
    image: dimitarpavlovski/wireup-backend
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - app_network


  frontend:
    image: dimitarpavlovski/wireup
    container_name: frontend
    depends_on:
      - mongodb
      - backend
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
    name: wireup_network